module.exports = {
    TICKS_PER_SECOND: 3,
    LENGTH_LANES: 1000,
    NUM_LANES: 2,
    PLAYER_INCOME: 1,
    PLAYER_START_MONEY: 3,
    SOLDIER_SPEED: 9,
    SOLDIER_DAMAGE: 2,
    SOLDIER_START: 3,
    SOLDIER_COST: 7,
    WORKER_SPEED: 5,
    WORKER_DAMAGE: 1,
    WORKER_START: 0,
    WORKER_COST: 3
}
